apiVersion: v2
name: pygwalker-demo
description: pygwalker demo for onyxia
icon: https://img.stackshare.io/service/48736/default_4e0283db2d5888961e64dca45605f779d2231d0c.png
keywords:
  - voila
  - Jupyter
home: https://voila-gallery.org
sources:
  - https://github.com/djangoliv/pygwalker-demo
  - https://forge.extranet.logilab.fr/open-source/onyxia/helm-charts-logilab-services
  - https://github.com/InseeFrLab/helm-charts-interactive-services
# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)

version: 0.0.1

dependencies:
  - name: library-chart
    version: 1.5.21
    repository: https://inseefrlab.github.io/helm-charts-interactive-services
