FROM inseefrlab/onyxia-python-datascience

USER root

COPY . /srv/
RUN pip install -U jupyterlab ipywidgets voila --no-cache
RUN if [ -f "/srv/requirements.txt" ]; then pip --no-cache install -U -r /srv/requirements.txt; fi
RUN if [ -f "/srv/environment.yml" ]; then conda env update -n root -f /srv/environment.yml; \
    echo "Warning; Issues may arise when using pip and conda together."; fi

USER 1000
EXPOSE 8888

CMD ["voila", "/srv/${NOTEBOOK_NAME}", "--Voila.ip='0.0.0.0'", "--port=8888", "--no-browser"]
