name: Build and push container images

# Trigger this workflow on pushes to main branches under the images folder or
# in PRs to the main branch that change the image folder
on:
  push:
    branches:
      - main
      - ci-test
    # paths:
    #   - "images/**"

# When multiple PRs triggering this workflow are merged, queue them instead
# of running them in parallel in case of clashes when pushing
# https://github.blog/changelog/2021-04-19-github-actions-limit-workflow-run-or-job-concurrency/
concurrency: image-build

jobs:
  # This job establishes from filepaths changed which images will be built by the
  # next job
  generate-build-matrix:
    runs-on: ubuntu-latest
    outputs:
      images-to-build: ${{ env.images-to-build }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install script requirements
        run: python -m pip install -r scripts/requirements.txt

      - name: Identify files that have been added or modified
        # Action repo: https://github.com/dorny/paths-filter
        # Fork of the repo above that we use: https://github.com/frouioui/paths-filter/tree/main
        # In order to take advantage of https://github.com/dorny/paths-filter/pull/133
        uses: frouioui/paths-filter@main
        id: changed-files
        with:
          token: ""
          list-files: csv
          filters: |
            changed:
              - added|modified: images/**

      - name: Generate matrix jobs
        run: |
          python scripts/generate-image-build-matrix-jobs.py "${{ steps.changed-files.outputs.changed_files }}"

  build-and-push:
    environment: docker-registry
    runs-on: ubuntu-latest
    needs: [generate-build-matrix]
    strategy:
      matrix:
        jobs: ${{ fromJson(needs.generate-build-matrix.outputs.images-to-build) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: registry.logilab.fr/open-source/dockerfiles/onyxia/${{ matrix.jobs.image-name }}
          tags: |
            type=raw,value=latest
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to registry
        uses: docker/login-action@v1
        with:
          registry: registry.logilab.fr
          username: token
          password: ${{ secrets.DOCKER_REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: images/${{ matrix.jobs.image-name }}
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          secrets: |
            GIT_AUTH_TOKEN=${{ secrets.DOCKER_REGISTRY_TOKEN }}
